name: Build

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]

jobs:
  build:
    strategy:
      matrix:
        temurin_tag:
          - 8u322-b06-jre
          - 11.0.14.1_1-jre
          - 8u322-b06-jdk
          - 11.0.14.1_1-jdk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Push Docker Image
        uses: ./.github/actions/build
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          TEMURIN_TAG: ${{ matrix.temurin_tag }}
      - name: Active Snyk Project
        if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
        run: ./scripts/activate-snyk-project.sh java ${{ matrix.temurin_tag }} $(git rev-parse --short "$GITHUB_SHA")
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}