name: Build

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main]
    tags: [v*]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    strategy:
      matrix:
        temurin_tag:
          - 11.0.32_9-jre
          - 11.0.32_9-jdk
          - 17.0.20_8-jre
          - 17.0.20_8-jdk
          - 21.0.12_8-jre
          - 21.0.12_8-jdk
          - 25.0.4_7-jre
          - 25.0.4_7-jdk

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dwolla/java
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Push Docker Image
        uses: Dwolla/jenkins-agents-workflow/.github/actions/build@main
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          BASE_TAG: ${{ matrix.TEMURIN_TAG }}
          TAG_NAME: TEMURIN_TAG
          IMAGE_NAME: dwolla/java
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
      - name: Build Image For Scanning
        run: docker buildx build --load --platform linux/amd64 --build-arg TEMURIN_TAG=${{ matrix.temurin_tag }} --tag "$IMAGE_NAME:scan" .
      - name: Snyk Container Test
        run: snyk container test "$IMAGE_NAME:scan" --file=Dockerfile --org=dwolla || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Container Monitor
        if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
        run: snyk container monitor "$IMAGE_NAME:${{ matrix.temurin_tag }}-${GITHUB_SHA::7}" --file=Dockerfile --org=dwolla
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  build-complete:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: '[ "${{ needs.build.result }}" = "success" ]'
